<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<section xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xi="http://www.w3.org/2001/XInclude" version="5.1">
  <title>Troubleshooting your Barbican Setup</title>
  <para>If you cannot find the answers you’re looking for within this document,
            you can ask questions on the Freenode IRC channel <literal>#openstack-barbican</literal></para>
  <section>
    <title>Getting a Barbican HTTP 401 error after a successful authentication to Keystone</title>
    <section>
      <title>What you might see</title>
      <para>You get a HTTP 401 Unauthorized response even with a valid token</para>
      <screen language="bash">curl -X POST -H "X-Auth-Token: $TOKEN" -H "Content-type: application/json" \
-d '{"payload": "my-secret-here", "payload_content_type": "text/plain"}' \
http://localhost:9311/v1/secrets</screen>
    </section>
    <section>
      <title>Caused by</title>
      <para>Expired signing cert on the Barbican server.</para>
    </section>
    <section>
      <title>How to avoid</title>
      <para>Check for an expired Keystone signing certificate on your Barbican server.
                    Look at the expiration date in <literal>/tmp/barbican/cache/signing_cert.pem</literal>. If
                    it is expired then follow these steps.</para>
      <procedure>
        <step>
          <para>On your Keystone server, verify that signing_cert.pem has the same
                                expiration date as the one on your Barbican machine. You can normally find
                                <literal>signing_cert.pem</literal> on your Keystone server in <literal>/etc/keystone/ssl/certs</literal>.</para>
        </step>
        <step>
          <para>If the cert matches then follow these steps to create a new one</para>
          <procedure>
            <step>
              <para>Delete it from both your Barbican and Keystone servers.</para>
            </step>
            <step>
              <para>Edit <literal>/etc/keystone/ssl/certs/index.txt.attr</literal> and set unique_subject
                                        to no.</para>
            </step>
            <step>
              <para>Run <literal>keystone-manage pki_setup</literal> to create a new <literal>signing_cert.pem</literal></para>
            </step>
            <step>
              <para>The updated cert will be downloaded to your Barbican server the next
                                        time you hit the Barbican API.</para>
            </step>
          </procedure>
        </step>
        <step>
          <para>If the cert <emphasis role="bold">doesn’t match</emphasis> then delete the <literal>signing_cert.pem</literal> from
                                your Barbican server. Do not delete from Keystone. The cert from Keystone
                                will be downloaded to your machine the next time you hit the Barbican API.</para>
        </step>
      </procedure>
    </section>
  </section>
  <section>
    <title>Returned refs use localhost instead of the correct hostname</title>
    <section>
      <title>What you might see</title>
      <screen language="bash">curl -X POST \
-H "Content-type: application/json" -H "X-Auth-Token: $TOKEN" -d \
'{"payload": "my-secret-here", "payload_content_type": "text/plain"}' \
http://myhostname.com/v1/secrets

# Response:
{
  "secret_ref": "http://localhost:9311/v1/secrets/UUID_HERE"
}</screen>
    </section>
    <section>
      <title>Caused by</title>
      <para>The default configuration on the response host name is not modified to the
                    endpoint’s host name (typically the load balancer’s DNS name and port).</para>
    </section>
    <section>
      <title>How to avoid</title>
      <para>Change your <literal>barbican.conf</literal> file’s <literal>host_href</literal> setting from
                    <literal>localhost:9311</literal> to the correct host name (myhostname.com in the example
                    above).</para>
    </section>
  </section>
  <section>
    <title>Barbican’s tox tests fail to run on my Mac</title>
    <section>
      <title>What you might see</title>
      <para>
        <literal>clang: error: unknown argument: '-mno-fused-madd'</literal>
      </para>
    </section>
    <section>
      <title>How to avoid</title>
      <para>There is a <link xlink:href="https://langui.sh/2014/03/10/wunused-command-line-argument-hard-error-in-future-is-a-harsh-mistress/">great blog article</link> that provides more details on the error and
                    how to work around it. This link provides more details on the error and how
                    to work around it.</para>
    </section>
  </section>
  <section>
    <title>Barbican’s tox tests fail to find ffi.h on my Mac</title>
    <section>
      <title>What you might see</title>
      <screen language="text">c/_cffi_backend.c:13:10: fatal error: 'ffi.h' file not found
...
ERROR: could not install deps [...]; v = InvocationError('...', 1)</screen>
    </section>
    <section>
      <title>How to avoid</title>
      <para>Be sure that xcode and cmd line tools are up to date. Easiest way is to run
                    <literal>xcode-select --install</literal> from an OS X command line. Be sure to say yes when
                    asked if you want to install the command line tools. Now
                    <literal>ls /usr/include/ffi/ffi.h</literal> should show that missing file exists, and the tox
                    tests should run.</para>
    </section>
  </section>
  <section>
    <title>Barbican’s tox tests fail with “ImportError: No module named _bsddb”</title>
    <section>
      <title>What you might see</title>
      <screen language="text">ImportError: No module named _bsddb</screen>
    </section>
    <section>
      <title>How to avoid</title>
      <para>Running tests via tox (which uses testr) will create a .testrepository directory containing, among other things, data files.  Those datafiles may be created with bsddb, if it is available in the environment. This can cause problems if you run in an environment that does not have bsddb.  To resolve this, delete your .testrepository directory and run tox again.</para>
    </section>
  </section>
  <section>
    <title>uWSGI logs ‘OOPS ! failed loading app’</title>
    <section>
      <title>What you might see</title>
      <screen language="text">...
spawned uWSGI master process (pid: 59190)
spawned uWSGI worker 1 (pid: 59191, cores: 1)
spawned uWSGI worker 1 (pid: 59192, cores: 1)
Loading paste environment: config:/etc/barbican/barbican-api-paste.ini
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter \
    0x7fd098c08520 pid: 59191 (default app)
OOPS ! failed loading app in worker 1 (pid 59192) :( trying again...
Respawned uWSGI worker 1 (new pid: 59193)
Loading paste environment: config:/etc/barbican/barbican-api-paste.ini
OOPS ! failed loading app in worker 1 (pid 59193) :( trying again...
worker respawning too fast !!! i have to sleep a bit (2 seconds)...
...</screen>
      <note>
        <para>You will not see any useful logs or stack traces with this error!</para>
      </note>
    </section>
    <section>
      <title>Caused by</title>
      <para>The vassal (worker) processes are not able to access the datastore.</para>
    </section>
    <section>
      <title>How to avoid</title>
      <para>Check the <literal>sql_connection</literal> in your <literal>barbican.conf</literal> file, to make sure
                    that it references a valid reachable database.</para>
    </section>
  </section>
  <section>
    <title>“Cannot register CLI option” error when importing logging</title>
    <section>
      <title>What you might see</title>
      <screen language="text">...
File ".../oslo_config/cfg.py", line 1275, in register_cli_opt
raise ArgsAlreadyParsedError("cannot register CLI option")
ArgsAlreadyParsedError: arguments already parsed: cannot register CLI option</screen>
    </section>
    <section>
      <title>Caused by</title>
      <para>An attempt to call the olso.config’s <literal>register_cli_opt()</literal> function after the
                    configuration arguments were ‘parsed’ (see the comments and method in
                    <link xlink:href="https://github.com/openstack/oslo.config/blob/master/oslo_config/cfg.py">the oslo.config project’s cfg.py file</link> for details.</para>
    </section>
    <section>
      <title>How to avoid</title>
      <para>Instead of calling <literal>import barbican.openstack.common.log as logging</literal> to get a
                    logger, call <literal>from barbican.common import config</literal> with this to get a logger
                    to use in your source file: <literal>LOG = config.getLogger(__name__)</literal>.</para>
    </section>
  </section>
  <section>
    <title>Responder raised TypeError: ‘NoneType’ object has no attribute ‘__getitem__’</title>
    <section>
      <title>What you might see</title>
      <screen language="text">...
2013-04-14 14:17:56 [FALCON] [ERROR] POST \
/da71dfbc-a959-4ad3-bdab-5ee190ce7515/csrs? =&gt; Responder raised \
TypeError: 'NoneType' object has no attribute '__getitem__'</screen>
    </section>
    <section>
      <title>Caused by</title>
      <para>Forgetting to set your non-nullable FKs in entities you create via
                    <literal>XxxxResource</literal> classes.</para>
    </section>
    <section>
      <title>How to avoid</title>
      <para>Don’t forget to set any FKs defined on an entity prior to using the repository
                    to create it.</para>
    </section>
  </section>
  <section>
    <title>uWSGI config issue: <literal>ImportError: No module named site</literal></title>
    <section>
      <title>What you might see</title>
      <screen language="text">...
uwsgi socket 0 bound to TCP address :9311 fd 3
Python version: 2.7.3 (...)  [...]
Set PythonHome to ./.venv
ImportError: No module named site</screen>
    </section>
    <section>
      <title>Caused by</title>
      <itemizedlist>
        <listitem>
          <para>Can’t locate the Python virtualenv for the Barbican project.</para>
        </listitem>
        <listitem>
          <para>Either the ‘broker’ setting above is incorrect, or else you haven’t started a
                            queue process yet (such as RabbitMQ)</para>
        </listitem>
      </itemizedlist>
    </section>
    <section>
      <title>How to avoid</title>
      <para>Make sure the uWSGI config file at <literal>etc/barbican/barbican-api-paste.ini</literal> is
                    configured correctly (see installation steps above), esp. if the virtualenv
                    folder is named differently than the <literal>.ini</literal> file has.</para>
    </section>
  </section>
  <section>
    <title>REST Request Fails with JSON error</title>
    <section>
      <title>What you might see</title>
      <screen language="json">{
    title: "Malformed JSON"
}</screen>
    </section>
    <section>
      <title>Caused by</title>
      <para>Barbican REST server cannot parse the incoming JSON message from your REST
                    client.</para>
    </section>
    <section>
      <title>How to avoid</title>
      <para>Make sure you are submitting properly formed JSON. For example, are there
                    commas after all but the last name/value pair in a list? Are there quotes
                    around all name/values that are text-based? Are the types of values matching
                    what is expected (i.e. integer and boolean types instead of quoted text)?</para>
      <para>If you are using the Advanced REST Client with Chrome, and you tried to
                    upload a file to the secrets PUT call, not only will this fail due to the
                    multi-part format it uses, but it will also try to submit this file for every
                    REST request you make thereafter, causing this error. Close the tab/window
                    with the client, and restart it again.</para>
    </section>
  </section>
  <section>
    <title>Crypto Mime Type Not Supported when I try to run tests or hit the API</title>
    <section>
      <title>What you might see</title>
      <para>A stack trace that has this in it (for example):</para>
      <screen language="text">CryptoMimeTypeNotSupportedException: Crypto Mime Type of 'text/plain' not \
supported</screen>
    </section>
    <section>
      <title>Caused by</title>
      <para>The Barbican plugins are not installed into a place where the Python plugin
                    manager can find them.</para>
    </section>
    <section>
      <title>How to avoid</title>
      <para>Make sure you run the <literal>pip install -e .</literal>.</para>
    </section>
  </section>
  <section>
    <title>Python “can’t find module errors” with the uWSGI scripts</title>
    <section>
      <title>What you might see</title>
      <screen language="text">*** has_emperor mode detected (fd: 6) ***
...
!!! UNABLE to load uWSGI plugin: dlopen(./python_plugin.so, 10): image not \
found !!!
...
File "./site-packages/paste/deploy/loadwsgi.py", line 22, in import_string
  return pkg_resources.EntryPoint.parse("x=" + s).load(False)
File "./site-packages/distribute-0.6.35-py2.7.egg/pkg_resources.py", line \
2015, in load
  entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named barbican.api.app
...
*** Starting uWSGI 1.9.13 (64bit) on [Fri Jul  5 09:59:29 2013] ***</screen>
    </section>
    <section>
      <title>Caused by</title>
      <para>The Barbican source modules are not found in the Python path of applications
                    such as uwsgi.</para>
    </section>
    <section>
      <title>How to avoid</title>
      <para>Make sure you are running from your virtual env, and that pip was executed
                    <emphasis role="bold">after</emphasis> you activated your virtual environment. This especially includes the
                    <literal>pip install -e</literal> command. Also, it is possible that your virtual env gets
                    corrupted, so you might need to rebuild it.</para>
    </section>
  </section>
  <section>
    <title>‘unable to open database file None None’ errors running scripts</title>
    <section>
      <title>What you might see</title>
      <screen language="text">...
File "./site-packages/sqlalchemy/engine/strategies.py", line 80, in connect
  return dialect.connect(*cargs, **cparams)
File "./site-packages/sqlalchemy/engine/default.py", line 283, in connect
  return self.dbapi.connect(*cargs, **cparams)
OperationalError: (OperationalError) unable to open database file None None
[emperor] removed uwsgi instance barbican-api.ini
...</screen>
    </section>
    <section>
      <title>Caused by</title>
      <para>Destination folder for the sqlite database is not found, or is not writable.</para>
    </section>
    <section>
      <title>How to avoid</title>
      <para>Make sure the <literal>/var/lib/barbican/</literal> folder exists and is writable by the user
                    that is running the Barbican API process.</para>
    </section>
  </section>
  <section>
    <title>‘ValueError: No JSON object could be decoded’ with Keystoneclient middleware</title>
    <section>
      <title>What you might see</title>
      <screen language="text">...
2013-08-15 16:55:15.759 2445 DEBUG keystoneclient.middleware.auth_token \
[-] Token validation failure. _validate_user_token \
./site-packages/keystoneclient/middleware/auth_token.py:711
...
2013-08-15 16:55:15.759 2445 TRACE keystoneclient.middleware.auth_token \
raise ValueError("No JSON object could be decoded")
2013-08-15 16:55:15.759 24458 TRACE keystoneclient.middleware.auth_token \
ValueError: No JSON object could be decoded
...
2013-08-15 16:55:15.766 2445 WARNING keystoneclient.middleware.auth_token \
[-] Authorization failed for token ...
2013-08-15 16:55:15.766 2445 INFO keystoneclient.middleware.auth_token \
[-] Invalid user token - rejecting request...</screen>
    </section>
    <section>
      <title>Caused by</title>
      <para>The <literal>keystoneclient</literal> middleware component is looking for a <literal>cms</literal> command in
                    <literal>openssl</literal> that wasn’t available before version <literal>1.0.1</literal>.</para>
    </section>
    <section>
      <title>How to avoid</title>
      <para>Update openssl.</para>
    </section>
  </section>
  <section>
    <title>“accept-encoding of ‘gzip,deflate,sdch’ not supported”</title>
    <section>
      <title>What you might see</title>
      <screen language="text">Secret retrieval issue seen - accept-encoding of 'gzip,deflate,sdch' not \
supported</screen>
    </section>
    <section>
      <title>Caused by</title>
      <para>This might be an issue with the browser you are using, as performing the
                    request via curl doesn’t seem to be affected.</para>
    </section>
    <section>
      <title>How to avoid</title>
      <para>Other than using an command such as curl to make the REST request you may not
                    have many other options.</para>
    </section>
  </section>
</section>
